# Generated by Django 5.2.7 on 2026-02-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumBlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
    ]
