# Generated by Django 6.0.2 on 2026-02-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumBlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
    ]
