# Generated by Django 5.2.7 on 2026-01-23 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HeartBlock', '0004_alter_member_age_alter_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('date', models.DateTimeField(verbose_name='Дата та час')),
                ('location', models.CharField(default='Онлайн', max_length=100, verbose_name='Місце проведення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='HeartBlock.group')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
