# Generated by Django 5.2.7 on 2026-01-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventsBlock', '0001_initial'),
        ('HeartBlock', '0005_groupcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Основний текст')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='Умови/Деталі')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImgCell/Announcements/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ann_linked', to='EventsBlock.event', verbose_name="Пов'язана подія")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='HeartBlock.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
