# Generated by Django 5.2.7 on 2026-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnBlock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='manual_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/Час (вручну)'),
        ),
    ]
