# Generated by Django 5.2.7 on 2026-01-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnBlock', '0002_announcement_manual_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='StaticBlock/ImgCell/Announcements/', verbose_name='Зображення'),
        ),
    ]
