# Generated by Django 5.2.7 on 2026-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnBlock', '0003_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='StaticBlock/ImgCell/Announcements/'),
        ),
    ]
