# Generated by Django 5.2.7 on 2026-01-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('code_number', models.CharField(max_length=20, unique=True, verbose_name='Кодовий номер')),
                ('group_type', models.CharField(choices=[('tech', 'Технології'), ('art', 'Мистецтво'), ('science', 'Наука'), ('social', 'Соціальність'), ('sport', 'Спорт'), ('music', 'Музика'), ('edu', 'Освіта'), ('eco', 'Екологія'), ('charity', 'Благодійництво'), ('game', 'Ігри'), ('photo', 'Фотографія'), ('cook', 'Кулінарія'), ('travel', 'Подорожі'), ('cinema', 'Кінематограф'), ('design', 'Дизайн'), ('fashion', 'Мода'), ('it', 'IT-розробка'), ('crypto', 'Криптовалюти'), ('history', 'Історія'), ('lit', 'Література'), ('health', "Здоров'я"), ('auto', 'Транспорт'), ('business', 'Бізнес'), ('space', 'Астрономія')], default='tech', max_length=30, verbose_name='Тип групи')),
                ('group_bio', models.TextField(blank=True, verbose_name='Опис групи')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('age', models.PositiveIntegerField(verbose_name='Вік')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='HeartBlock.group', to_field='code_number', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Учасник / Користувач',
                'verbose_name_plural': 'Учасники / Користувачі',
            },
        ),
    ]
