# Generated by Django 5.2.7 on 2026-01-10 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBlock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Ліміт учасників'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='code_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('tech', 'Технології'), ('art', 'Мистецтво'), ('science', 'Наука'), ('social', 'Соціальність'), ('sport', 'Спорт'), ('music', 'Музика'), ('edu', 'Освіта'), ('eco', 'Екологія'), ('charity', 'Благодійництво'), ('game', 'Ігри'), ('photo', 'Фотографія'), ('cook', 'Кулінарія'), ('travel', 'Подорожі'), ('cinema', 'Кінематограф'), ('design', 'Дизайн'), ('fashion', 'Мода'), ('it', 'IT-розробка'), ('crypto', 'Криптовалюти'), ('history', 'Історія'), ('lit', 'Література'), ('health', "Здоров'я"), ('auto', 'Транспорт'), ('business', 'Бізнес'), ('space', 'Астрономія')], default='tech', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='HeartBlock.group', to_field='code_number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
