# Generated by Django 5.2.7 on 2026-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBlock', '0002_alter_group_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
