# Generated by Django 5.2.7 on 2026-01-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBlock', '0005_groupcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='StaticBlock/ImgCell/Avatars/'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
