# Generated by Django 5.2.7 on 2026-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBlock', '0006_member_avatar_member_is_premium_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar_border',
            field=models.CharField(blank=True, choices=[('none', 'Немає'), ('neon', 'Неон'), ('gold', 'Золото'), ('fire', 'Вогонь')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('none', 'Не визначено'), ('male', 'Чоловік'), ('female', 'Жінка')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_bg',
            field=models.CharField(blank=True, choices=[('default', 'Стандартний'), ('space', 'Космос'), ('sunset', 'Захід сонця'), ('cyber', 'Кіберпанк')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
